// Horizon Design System · Tailwind preset
// Drop into your tailwind.config.js:  presets: [require('./tailwind.tokens.js')]
// Imports CSS variables from variables.css + tokens.css — load those in your global CSS.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "surface": {
          "border": "var(--surface-border)",
          "destructive-background": "var(--surface-destructive-background)",
          "page-background-content": "var(--surface-page-background-content)",
          "warning-background": "var(--surface-warning-background)",
          "card-background": "var(--surface-card-background)",
          "page-background-backlight": "var(--surface-page-background-backlight)",
          "header-background": "var(--surface-header-background)",
          "navigation-background": "var(--surface-navigation-background)",
          "widget-background": "var(--surface-widget-background)",
          "muted-background": "var(--surface-muted-background)",
          "overlay-background": "var(--surface-overlay-background)",
          "success-background": "var(--surface-success-background)"
        },
        "text": {
          "white": "var(--text-white)",
          "black": "var(--text-black)",
          "primary": "var(--text-primary)",
          "secondary": "var(--text-secondary)",
          "tertiary": "var(--text-tertiary)",
          "destructive": "var(--text-destructive)",
          "warning": "var(--text-warning)",
          "success": "var(--text-success)",
          "url": "var(--text-url)"
        },
        "charts": {
          "chart-1": "var(--chart-1)",
          "chart-2": "var(--chart-2)",
          "chart-3": "var(--chart-3)",
          "chart-4": "var(--chart-4)",
          "chart-5": "var(--chart-5)"
        },
        "alpha": {
          "10": "var(--alpha-10)",
          "20": "var(--alpha-20)",
          "30": "var(--alpha-30)",
          "40": "var(--alpha-40)",
          "50": "var(--alpha-50)",
          "60": "var(--alpha-60)",
          "70": "var(--alpha-70)",
          "80": "var(--alpha-80)",
          "90": "var(--alpha-90)"
        },
        "primitive": {
          "base-black": "var(--base-black)",
          "base-white": "var(--base-white)",
          "base-transparent": "var(--base-transparent)",
          "slate-slate-50": "var(--slate-slate-50)",
          "slate-slate-100": "var(--slate-slate-100)",
          "slate-slate-200": "var(--slate-slate-200)",
          "slate-slate-300": "var(--slate-slate-300)",
          "slate-slate-400": "var(--slate-slate-400)",
          "slate-slate-500": "var(--slate-slate-500)",
          "slate-slate-600": "var(--slate-slate-600)",
          "slate-slate-700": "var(--slate-slate-700)",
          "slate-slate-800": "var(--slate-slate-800)",
          "slate-slate-900": "var(--slate-slate-900)",
          "slate-slate-950": "var(--slate-slate-950)",
          "gray-gray-50": "var(--gray-gray-50)",
          "gray-gray-100": "var(--gray-gray-100)",
          "gray-gray-200": "var(--gray-gray-200)",
          "gray-gray-300": "var(--gray-gray-300)",
          "gray-gray-400": "var(--gray-gray-400)",
          "gray-gray-500": "var(--gray-gray-500)",
          "gray-gray-600": "var(--gray-gray-600)",
          "gray-gray-700": "var(--gray-gray-700)",
          "gray-gray-800": "var(--gray-gray-800)",
          "gray-gray-900": "var(--gray-gray-900)",
          "gray-gray-950": "var(--gray-gray-950)",
          "zinc-zinc-50": "var(--zinc-zinc-50)",
          "zinc-zinc-100": "var(--zinc-zinc-100)",
          "zinc-zinc-200": "var(--zinc-zinc-200)",
          "zinc-zinc-300": "var(--zinc-zinc-300)",
          "zinc-zinc-400": "var(--zinc-zinc-400)",
          "zinc-zinc-500": "var(--zinc-zinc-500)",
          "zinc-zinc-600": "var(--zinc-zinc-600)",
          "zinc-zinc-700": "var(--zinc-zinc-700)",
          "zinc-zinc-800": "var(--zinc-zinc-800)",
          "zinc-zinc-900": "var(--zinc-zinc-900)",
          "zinc-zinc-950": "var(--zinc-zinc-950)",
          "neutral-neutral-50": "var(--neutral-neutral-50)",
          "neutral-neutral-100": "var(--neutral-neutral-100)",
          "neutral-neutral-200": "var(--neutral-neutral-200)",
          "neutral-neutral-300": "var(--neutral-neutral-300)",
          "neutral-neutral-400": "var(--neutral-neutral-400)",
          "neutral-neutral-500": "var(--neutral-neutral-500)",
          "neutral-neutral-600": "var(--neutral-neutral-600)",
          "neutral-neutral-700": "var(--neutral-neutral-700)",
          "neutral-neutral-800": "var(--neutral-neutral-800)",
          "neutral-neutral-900": "var(--neutral-neutral-900)",
          "neutral-neutral-950": "var(--neutral-neutral-950)",
          "stone-stone-50": "var(--stone-stone-50)",
          "stone-stone-100": "var(--stone-stone-100)",
          "stone-stone-200": "var(--stone-stone-200)",
          "stone-stone-300": "var(--stone-stone-300)",
          "stone-stone-400": "var(--stone-stone-400)",
          "stone-stone-500": "var(--stone-stone-500)",
          "stone-stone-600": "var(--stone-stone-600)",
          "stone-stone-700": "var(--stone-stone-700)",
          "stone-stone-800": "var(--stone-stone-800)",
          "stone-stone-900": "var(--stone-stone-900)",
          "stone-stone-950": "var(--stone-stone-950)",
          "red-red-50": "var(--red-red-50)",
          "red-red-100": "var(--red-red-100)",
          "red-red-200": "var(--red-red-200)",
          "red-red-300": "var(--red-red-300)",
          "red-red-400": "var(--red-red-400)",
          "red-red-500": "var(--red-red-500)",
          "red-red-600": "var(--red-red-600)",
          "red-red-700": "var(--red-red-700)",
          "red-red-800": "var(--red-red-800)",
          "red-red-900": "var(--red-red-900)",
          "red-red-950": "var(--red-red-950)",
          "orange-orange-50": "var(--orange-orange-50)",
          "orange-orange-100": "var(--orange-orange-100)",
          "orange-orange-200": "var(--orange-orange-200)",
          "orange-orange-300": "var(--orange-orange-300)",
          "orange-orange-400": "var(--orange-orange-400)",
          "orange-orange-500": "var(--orange-orange-500)",
          "orange-orange-600": "var(--orange-orange-600)",
          "orange-orange-700": "var(--orange-orange-700)",
          "orange-orange-800": "var(--orange-orange-800)",
          "orange-orange-900": "var(--orange-orange-900)",
          "orange-orange-950": "var(--orange-orange-950)",
          "amber-amber-50": "var(--amber-amber-50)",
          "amber-amber-100": "var(--amber-amber-100)",
          "amber-amber-200": "var(--amber-amber-200)",
          "amber-amber-300": "var(--amber-amber-300)",
          "amber-amber-400": "var(--amber-amber-400)",
          "amber-amber-500": "var(--amber-amber-500)",
          "amber-amber-600": "var(--amber-amber-600)",
          "amber-amber-700": "var(--amber-amber-700)",
          "amber-amber-800": "var(--amber-amber-800)",
          "amber-amber-900": "var(--amber-amber-900)",
          "amber-amber-950": "var(--amber-amber-950)",
          "yellow-yellow-50": "var(--yellow-yellow-50)",
          "yellow-yellow-100": "var(--yellow-yellow-100)",
          "yellow-yellow-200": "var(--yellow-yellow-200)",
          "yellow-yellow-300": "var(--yellow-yellow-300)",
          "yellow-yellow-400": "var(--yellow-yellow-400)",
          "yellow-yellow-500": "var(--yellow-yellow-500)",
          "yellow-yellow-600": "var(--yellow-yellow-600)",
          "yellow-yellow-700": "var(--yellow-yellow-700)",
          "yellow-yellow-800": "var(--yellow-yellow-800)",
          "yellow-yellow-900": "var(--yellow-yellow-900)",
          "yellow-yellow-950": "var(--yellow-yellow-950)",
          "lime-lime-50": "var(--lime-lime-50)",
          "lime-lime-100": "var(--lime-lime-100)",
          "lime-lime-200": "var(--lime-lime-200)",
          "lime-lime-300": "var(--lime-lime-300)",
          "lime-lime-400": "var(--lime-lime-400)",
          "lime-lime-500": "var(--lime-lime-500)",
          "lime-lime-600": "var(--lime-lime-600)",
          "lime-lime-700": "var(--lime-lime-700)",
          "lime-lime-800": "var(--lime-lime-800)",
          "lime-lime-900": "var(--lime-lime-900)",
          "lime-lime-950": "var(--lime-lime-950)",
          "green-green-50": "var(--green-green-50)",
          "green-green-100": "var(--green-green-100)",
          "green-green-200": "var(--green-green-200)",
          "green-green-300": "var(--green-green-300)",
          "green-green-400": "var(--green-green-400)",
          "green-green-500": "var(--green-green-500)",
          "green-green-600": "var(--green-green-600)",
          "green-green-700": "var(--green-green-700)",
          "green-green-800": "var(--green-green-800)",
          "green-green-900": "var(--green-green-900)",
          "green-green-950": "var(--green-green-950)",
          "emerald-emerald-50": "var(--emerald-emerald-50)",
          "emerald-emerald-100": "var(--emerald-emerald-100)",
          "emerald-emerald-200": "var(--emerald-emerald-200)",
          "emerald-emerald-300": "var(--emerald-emerald-300)",
          "emerald-emerald-400": "var(--emerald-emerald-400)",
          "emerald-emerald-500": "var(--emerald-emerald-500)",
          "emerald-emerald-600": "var(--emerald-emerald-600)",
          "emerald-emerald-700": "var(--emerald-emerald-700)",
          "emerald-emerald-800": "var(--emerald-emerald-800)",
          "emerald-emerald-900": "var(--emerald-emerald-900)",
          "emerald-emerald-950": "var(--emerald-emerald-950)",
          "teal-teal-50": "var(--teal-teal-50)",
          "teal-teal-100": "var(--teal-teal-100)",
          "teal-teal-200": "var(--teal-teal-200)",
          "teal-teal-300": "var(--teal-teal-300)",
          "teal-teal-400": "var(--teal-teal-400)",
          "teal-teal-500": "var(--teal-teal-500)",
          "teal-teal-600": "var(--teal-teal-600)",
          "teal-teal-700": "var(--teal-teal-700)",
          "teal-teal-800": "var(--teal-teal-800)",
          "teal-teal-900": "var(--teal-teal-900)",
          "teal-teal-950": "var(--teal-teal-950)",
          "cyan-cyan-50": "var(--cyan-cyan-50)",
          "cyan-cyan-100": "var(--cyan-cyan-100)",
          "cyan-cyan-200": "var(--cyan-cyan-200)",
          "cyan-cyan-300": "var(--cyan-cyan-300)",
          "cyan-cyan-400": "var(--cyan-cyan-400)",
          "cyan-cyan-500": "var(--cyan-cyan-500)",
          "cyan-cyan-600": "var(--cyan-cyan-600)",
          "cyan-cyan-700": "var(--cyan-cyan-700)",
          "cyan-cyan-800": "var(--cyan-cyan-800)",
          "cyan-cyan-900": "var(--cyan-cyan-900)",
          "cyan-cyan-950": "var(--cyan-cyan-950)",
          "sky-sky-50": "var(--sky-sky-50)",
          "sky-sky-100": "var(--sky-sky-100)",
          "sky-sky-200": "var(--sky-sky-200)",
          "sky-sky-300": "var(--sky-sky-300)",
          "sky-sky-400": "var(--sky-sky-400)",
          "sky-sky-500": "var(--sky-sky-500)",
          "sky-sky-600": "var(--sky-sky-600)",
          "sky-sky-700": "var(--sky-sky-700)",
          "sky-sky-800": "var(--sky-sky-800)",
          "sky-sky-900": "var(--sky-sky-900)",
          "sky-sky-950": "var(--sky-sky-950)",
          "blue-blue-50": "var(--blue-blue-50)",
          "blue-blue-100": "var(--blue-blue-100)",
          "blue-blue-200": "var(--blue-blue-200)",
          "blue-blue-300": "var(--blue-blue-300)",
          "blue-blue-400": "var(--blue-blue-400)",
          "blue-blue-500": "var(--blue-blue-500)",
          "blue-blue-600": "var(--blue-blue-600)",
          "blue-blue-700": "var(--blue-blue-700)",
          "blue-blue-800": "var(--blue-blue-800)",
          "blue-blue-900": "var(--blue-blue-900)",
          "blue-blue-950": "var(--blue-blue-950)",
          "indigo-indigo-50": "var(--indigo-indigo-50)",
          "indigo-indigo-100": "var(--indigo-indigo-100)",
          "indigo-indigo-200": "var(--indigo-indigo-200)",
          "indigo-indigo-300": "var(--indigo-indigo-300)",
          "indigo-indigo-400": "var(--indigo-indigo-400)",
          "indigo-indigo-500": "var(--indigo-indigo-500)",
          "indigo-indigo-600": "var(--indigo-indigo-600)",
          "indigo-indigo-700": "var(--indigo-indigo-700)",
          "indigo-indigo-800": "var(--indigo-indigo-800)",
          "indigo-indigo-900": "var(--indigo-indigo-900)",
          "indigo-indigo-950": "var(--indigo-indigo-950)",
          "violet-violet-50": "var(--violet-violet-50)",
          "violet-violet-100": "var(--violet-violet-100)",
          "violet-violet-200": "var(--violet-violet-200)",
          "violet-violet-300": "var(--violet-violet-300)",
          "violet-violet-400": "var(--violet-violet-400)",
          "violet-violet-500": "var(--violet-violet-500)",
          "violet-violet-600": "var(--violet-violet-600)",
          "violet-violet-700": "var(--violet-violet-700)",
          "violet-violet-800": "var(--violet-violet-800)",
          "violet-violet-900": "var(--violet-violet-900)",
          "violet-violet-950": "var(--violet-violet-950)",
          "purple-purple-50": "var(--purple-purple-50)",
          "purple-purple-100": "var(--purple-purple-100)",
          "purple-purple-200": "var(--purple-purple-200)",
          "purple-purple-300": "var(--purple-purple-300)",
          "purple-purple-400": "var(--purple-purple-400)",
          "purple-purple-500": "var(--purple-purple-500)",
          "purple-purple-600": "var(--purple-purple-600)",
          "purple-purple-700": "var(--purple-purple-700)",
          "purple-purple-800": "var(--purple-purple-800)",
          "purple-purple-900": "var(--purple-purple-900)",
          "purple-purple-950": "var(--purple-purple-950)",
          "fuchsia-fuchsia-50": "var(--fuchsia-fuchsia-50)",
          "fuchsia-fuchsia-100": "var(--fuchsia-fuchsia-100)",
          "fuchsia-fuchsia-200": "var(--fuchsia-fuchsia-200)",
          "fuchsia-fuchsia-300": "var(--fuchsia-fuchsia-300)",
          "fuchsia-fuchsia-400": "var(--fuchsia-fuchsia-400)",
          "fuchsia-fuchsia-500": "var(--fuchsia-fuchsia-500)",
          "fuchsia-fuchsia-600": "var(--fuchsia-fuchsia-600)",
          "fuchsia-fuchsia-700": "var(--fuchsia-fuchsia-700)",
          "fuchsia-fuchsia-800": "var(--fuchsia-fuchsia-800)",
          "fuchsia-fuchsia-900": "var(--fuchsia-fuchsia-900)",
          "fuchsia-fuchsia-950": "var(--fuchsia-fuchsia-950)",
          "pink-pink-50": "var(--pink-pink-50)",
          "pink-pink-100": "var(--pink-pink-100)",
          "pink-pink-200": "var(--pink-pink-200)",
          "pink-pink-300": "var(--pink-pink-300)",
          "pink-pink-400": "var(--pink-pink-400)",
          "pink-pink-500": "var(--pink-pink-500)",
          "pink-pink-600": "var(--pink-pink-600)",
          "pink-pink-700": "var(--pink-pink-700)",
          "pink-pink-800": "var(--pink-pink-800)",
          "pink-pink-900": "var(--pink-pink-900)",
          "pink-pink-950": "var(--pink-pink-950)",
          "rose-rose-50": "var(--rose-rose-50)",
          "rose-rose-100": "var(--rose-rose-100)",
          "rose-rose-200": "var(--rose-rose-200)",
          "rose-rose-300": "var(--rose-rose-300)",
          "rose-rose-400": "var(--rose-rose-400)",
          "rose-rose-500": "var(--rose-rose-500)",
          "rose-rose-600": "var(--rose-rose-600)",
          "rose-rose-700": "var(--rose-rose-700)",
          "rose-rose-800": "var(--rose-rose-800)",
          "rose-rose-900": "var(--rose-rose-900)",
          "rose-rose-950": "var(--rose-rose-950)"
        },
        "brand": {
          "al-indigo-50": "var(--al-indigo-50)",
          "al-indigo-100": "var(--al-indigo-100)",
          "al-indigo-200": "var(--al-indigo-200)",
          "al-indigo-300": "var(--al-indigo-300)",
          "al-indigo-400": "var(--al-indigo-400)",
          "al-indigo-500": "var(--al-indigo-500)",
          "al-indigo-600": "var(--al-indigo-600)",
          "al-indigo-700": "var(--al-indigo-700)",
          "al-indigo-800": "var(--al-indigo-800)",
          "al-indigo-900": "var(--al-indigo-900)",
          "al-indigo-950": "var(--al-indigo-950)",
          "al-teal-50": "var(--al-teal-50)",
          "al-teal-100": "var(--al-teal-100)",
          "al-teal-200": "var(--al-teal-200)",
          "al-teal-300": "var(--al-teal-300)",
          "al-teal-400": "var(--al-teal-400)",
          "al-teal-500": "var(--al-teal-500)",
          "al-teal-600": "var(--al-teal-600)",
          "al-teal-700": "var(--al-teal-700)",
          "al-teal-800": "var(--al-teal-800)",
          "al-teal-900": "var(--al-teal-900)",
          "al-teal-950": "var(--al-teal-950)",
          "mc-blue-50": "var(--mc-blue-50)",
          "mc-blue-100": "var(--mc-blue-100)",
          "mc-blue-200": "var(--mc-blue-200)",
          "mc-blue-300": "var(--mc-blue-300)",
          "mc-blue-400": "var(--mc-blue-400)",
          "mc-blue-500": "var(--mc-blue-500)",
          "mc-blue-600": "var(--mc-blue-600)",
          "mc-blue-700": "var(--mc-blue-700)",
          "mc-blue-800": "var(--mc-blue-800)",
          "mc-blue-900": "var(--mc-blue-900)",
          "mc-blue-950": "var(--mc-blue-950)",
          "mc-red-50": "var(--mc-red-50)",
          "mc-red-100": "var(--mc-red-100)",
          "mc-red-200": "var(--mc-red-200)",
          "mc-red-300": "var(--mc-red-300)",
          "mc-red-400": "var(--mc-red-400)",
          "mc-red-500": "var(--mc-red-500)",
          "mc-red-600": "var(--mc-red-600)",
          "mc-red-700": "var(--mc-red-700)",
          "mc-red-800": "var(--mc-red-800)",
          "mc-red-900": "var(--mc-red-900)",
          "mc-red-950": "var(--mc-red-950)",
          "bv-emerald-50": "var(--bv-emerald-50)",
          "bv-emerald-100": "var(--bv-emerald-100)",
          "bv-emerald-200": "var(--bv-emerald-200)",
          "bv-emerald-300": "var(--bv-emerald-300)",
          "bv-emerald-400": "var(--bv-emerald-400)",
          "bv-emerald-500": "var(--bv-emerald-500)",
          "bv-emerald-600": "var(--bv-emerald-600)",
          "bv-emerald-700": "var(--bv-emerald-700)",
          "bv-emerald-800": "var(--bv-emerald-800)",
          "bv-emerald-900": "var(--bv-emerald-900)",
          "bv-emerald-950": "var(--bv-emerald-950)",
          "bv-slate-50": "var(--bv-slate-50)",
          "bv-slate-100": "var(--bv-slate-100)",
          "bv-slate-200": "var(--bv-slate-200)",
          "bv-slate-300": "var(--bv-slate-300)",
          "bv-slate-400": "var(--bv-slate-400)",
          "bv-slate-500": "var(--bv-slate-500)",
          "bv-slate-600": "var(--bv-slate-600)",
          "bv-slate-700": "var(--bv-slate-700)",
          "bv-slate-800": "var(--bv-slate-800)",
          "bv-slate-900": "var(--bv-slate-900)",
          "bv-slate-950": "var(--bv-slate-950)",
          "wpr-yellow-50": "var(--wpr-yellow-50)",
          "wpr-yellow-100": "var(--wpr-yellow-100)",
          "wpr-yellow-200": "var(--wpr-yellow-200)",
          "wpr-yellow-300": "var(--wpr-yellow-300)",
          "wpr-yellow-400": "var(--wpr-yellow-400)",
          "wpr-yellow-500": "var(--wpr-yellow-500)",
          "wpr-yellow-600": "var(--wpr-yellow-600)",
          "wpr-yellow-700": "var(--wpr-yellow-700)",
          "wpr-yellow-800": "var(--wpr-yellow-800)",
          "wpr-yellow-900": "var(--wpr-yellow-900)",
          "wpr-yellow-950": "var(--wpr-yellow-950)",
          "wpr-stone-50": "var(--wpr-stone-50)",
          "wpr-stone-100": "var(--wpr-stone-100)",
          "wpr-stone-200": "var(--wpr-stone-200)",
          "wpr-stone-300": "var(--wpr-stone-300)",
          "wpr-stone-400": "var(--wpr-stone-400)",
          "wpr-stone-500": "var(--wpr-stone-500)",
          "wpr-stone-600": "var(--wpr-stone-600)",
          "wpr-stone-700": "var(--wpr-stone-700)",
          "wpr-stone-800": "var(--wpr-stone-800)",
          "wpr-stone-900": "var(--wpr-stone-900)",
          "wpr-stone-950": "var(--wpr-stone-950)"
        }
      },
      "borderRadius": {
        "0": "var(--radius-0)",
        "2": "var(--radius-2)",
        "4": "var(--radius-4)",
        "6": "var(--radius-6)",
        "8": "var(--radius-8)",
        "10": "var(--radius-10)",
        "12": "var(--radius-12)",
        "14": "var(--radius-14)",
        "16": "var(--radius-16)",
        "18": "var(--radius-18)",
        "20": "var(--radius-20)",
        "22": "var(--radius-22)",
        "24": "var(--radius-24)",
        "26": "var(--radius-26)",
        "28": "var(--radius-28)",
        "30": "var(--radius-30)",
        "32": "var(--radius-32)",
        "34": "var(--radius-34)",
        "36": "var(--radius-36)",
        "38": "var(--radius-38)",
        "40": "var(--radius-40)",
        "42": "var(--radius-42)",
        "44": "var(--radius-44)",
        "46": "var(--radius-46)",
        "48": "var(--radius-48)",
        "50": "var(--radius-50)",
        "52": "var(--radius-52)",
        "54": "var(--radius-54)",
        "56": "var(--radius-56)",
        "58": "var(--radius-58)",
        "60": "var(--radius-60)",
        "62": "var(--radius-62)",
        "64": "var(--radius-64)",
        "66": "var(--radius-66)",
        "68": "var(--radius-68)",
        "70": "var(--radius-70)",
        "72": "var(--radius-72)",
        "74": "var(--radius-74)",
        "76": "var(--radius-76)",
        "78": "var(--radius-78)",
        "80": "var(--radius-80)",
        "9999": "var(--radius-9999)"
      },
      "spacing": {
        "0": "var(--spacing-0)",
        "1": "var(--spacing-1)",
        "2": "var(--spacing-2)",
        "4": "var(--spacing-4)",
        "6": "var(--spacing-6)",
        "8": "var(--spacing-8)",
        "10": "var(--spacing-10)",
        "12": "var(--spacing-12)",
        "14": "var(--spacing-14)",
        "16": "var(--spacing-16)",
        "18": "var(--spacing-18)",
        "20": "var(--spacing-20)",
        "24": "var(--spacing-24)",
        "28": "var(--spacing-28)",
        "32": "var(--spacing-32)",
        "36": "var(--spacing-36)",
        "40": "var(--spacing-40)",
        "44": "var(--spacing-44)",
        "48": "var(--spacing-48)",
        "56": "var(--spacing-56)",
        "64": "var(--spacing-64)",
        "72": "var(--spacing-72)",
        "80": "var(--spacing-80)",
        "88": "var(--spacing-88)",
        "96": "var(--spacing-96)",
        "104": "var(--spacing-104)",
        "112": "var(--spacing-112)",
        "120": "var(--spacing-120)",
        "128": "var(--spacing-128)",
        "136": "var(--spacing-136)",
        "144": "var(--spacing-144)",
        "152": "var(--spacing-152)",
        "160": "var(--spacing-160)",
        "168": "var(--spacing-168)",
        "176": "var(--spacing-176)",
        "184": "var(--spacing-184)",
        "192": "var(--spacing-192)",
        "200": "var(--spacing-200)",
        "208": "var(--spacing-208)",
        "216": "var(--spacing-216)",
        "224": "var(--spacing-224)",
        "232": "var(--spacing-232)",
        "240": "var(--spacing-240)",
        "248": "var(--spacing-248)",
        "256": "var(--spacing-256)",
        "264": "var(--spacing-264)",
        "272": "var(--spacing-272)",
        "280": "var(--spacing-280)",
        "288": "var(--spacing-288)",
        "296": "var(--spacing-296)",
        "304": "var(--spacing-304)",
        "312": "var(--spacing-312)",
        "320": "var(--spacing-320)",
        "328": "var(--spacing-328)",
        "336": "var(--spacing-336)",
        "344": "var(--spacing-344)",
        "352": "var(--spacing-352)",
        "360": "var(--spacing-360)",
        "368": "var(--spacing-368)",
        "376": "var(--spacing-376)",
        "384": "var(--spacing-384)"
      },
      "screens": {
        "xs": "480px",
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "xl2": "1440px",
        "xl3": "1512px",
        "2xl": "1536px",
        "2xl2": "1728px",
        "3xl": "1920px",
        "4xl": "2560px",
        "5xl": "3440px",
        "6xl": "3840px",
        "7xl": "5120px",
        "8xl": "7680px"
      },
      "borderWidth": {
        "0": "var(--border-0)",
        "1": "var(--border-1)",
        "2": "var(--border-2)",
        "4": "var(--border-4)",
        "8": "var(--border-8)"
      },
      "opacity": {
        "0": "var(--opacity-0)",
        "5": "var(--opacity-5)",
        "10": "var(--opacity-10)",
        "15": "var(--opacity-15)",
        "20": "var(--opacity-20)",
        "25": "var(--opacity-25)",
        "30": "var(--opacity-30)",
        "35": "var(--opacity-35)",
        "40": "var(--opacity-40)",
        "45": "var(--opacity-45)",
        "50": "var(--opacity-50)",
        "55": "var(--opacity-55)",
        "60": "var(--opacity-60)",
        "65": "var(--opacity-65)",
        "70": "var(--opacity-70)",
        "75": "var(--opacity-75)",
        "80": "var(--opacity-80)",
        "85": "var(--opacity-85)",
        "90": "var(--opacity-90)",
        "95": "var(--opacity-95)",
        "100": "var(--opacity-100)"
      },
      "blur": {
        "none": "var(--blur-none)",
        "sm": "var(--blur-sm)",
        "base": "var(--blur-base)",
        "md": "var(--blur-md)",
        "lg": "var(--blur-lg)",
        "xl": "var(--blur-xl)",
        "2xl": "var(--blur-2xl)",
        "3xl": "var(--blur-3xl)"
      },
      "backdropBlur": {
        "none": "var(--backdrop-blur-none)",
        "sm": "var(--backdrop-blur-sm)",
        "base": "var(--backdrop-blur-base)",
        "md": "var(--backdrop-blur-md)",
        "lg": "var(--backdrop-blur-lg)",
        "xl": "var(--backdrop-blur-xl)",
        "2xl": "var(--backdrop-blur-2xl)",
        "3xl": "var(--backdrop-blur-3xl)"
      },
      "fontFamily": {
        "sans": [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ]
      },
      "fontSize": {
        "xs": [
          "12px",
          "16px"
        ],
        "sm": [
          "14px",
          "20px"
        ],
        "base": [
          "16px",
          "24px"
        ],
        "lg": [
          "18px",
          "28px"
        ],
        "xl": [
          "20px",
          "28px"
        ],
        "2xl": [
          "24px",
          "32px"
        ],
        "3xl": [
          "30px",
          "36px"
        ],
        "4xl": [
          "36px",
          "40px"
        ],
        "5xl": [
          "48px",
          "52px"
        ],
        "6xl": [
          "60px",
          "64px"
        ],
        "7xl": [
          "72px",
          "76px"
        ]
      },
      "fontWeight": {
        "thin": "var(--font-weight-thin)",
        "extralight": "var(--font-weight-extralight)",
        "light": "var(--font-weight-light)",
        "normal": "var(--font-weight-normal)",
        "medium": "var(--font-weight-medium)",
        "semibold": "var(--font-weight-semibold)",
        "bold": "var(--font-weight-bold)",
        "extrabold": "var(--font-weight-extrabold)",
        "black": "var(--font-weight-black)"
      },
      "letterSpacing": {
        "tighter": "var(--tracking-tighter)",
        "tight": "var(--tracking-tight)",
        "normal": "var(--tracking-normal)",
        "wide": "var(--tracking-wide)",
        "wider": "var(--tracking-wider)",
        "widest": "var(--tracking-widest)"
      },
      "boxShadow": {
        "sm": "var(--shadow-sm)",
        "base": "var(--shadow-base)",
        "md": "var(--shadow-md)",
        "lg": "var(--shadow-lg)",
        "xl": "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        "inner": "var(--shadow-inner)"
      }
    }
  }
};
